# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Deep Learning Basics (lecture notes)"
author: Romain Tavenard

# Bibliography
bibtex_bibfiles:
  - content/references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    nb_merge_streams: true
    tikz_proc_suite: pdf2svg
  extra_extensions:
  - sphinxcontrib.tikz
  - sphinx_proof


parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - dollarmath
    - amsmath

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/rtavenar/deep_book  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

latex:
  latex_documents:
    targetname: book.tex
  latex_engine: xelatex
